import { createClient } from '@/lib/supabase/server'
import { NextResponse } from 'next/server'
import { GoogleGenAI } from '@google/genai'

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY })

export async function POST(req: Request) {
    try {
        const supabase = await createClient()

        // 1. Get stored tokens to identify the user
        const { data: tokenRow, error: tokenErr } = await supabase
            .from('youtube_tokens')
            .select('*')
            .limit(1)
            .single()
        
        if (tokenErr || !tokenRow) {
            return NextResponse.json({ error: 'Unauthorized or YouTube not connected' }, { status: 401 })
        }
        
        const body = await req.json()
        const { videoUrl } = body

        if (!videoUrl) {
            return NextResponse.json({ error: 'Video URL is required' }, { status: 400 })
        }

        const prompt = `
You are an expert YouTube retention and engagement analyst.
Please review the following YouTube video: ${videoUrl}

Provide a "Video Autopsy" report in Markdown format.
Focus specifically on the HOOK (the first 30-60 seconds) and the overall retention strategy.

Include:
1. Hook Analysis (Did it deliver on the title/thumbnail promise? Was it engaging?)
2. Pacing & Editing (Are there dead spaces? Good use of b-roll or pattern interrupts?)
3. Story/Structure (Is there a clear payoff established?)
4. Verdict & Recommendations (What failed or succeeded, and how to improve the next video's hook).
`

        // Call Gemini 3.1 Pro Preview Native Video Parsing
        const response = await ai.models.generateContent({
            model: 'gemini-3.1-pro-preview',
            contents: prompt,
            config: {
                temperature: 0.7,
            }
        })

        if (!response.text) {
            throw new Error('No text generated by Gemini')
        }

        // Note: Skipped storing into youtube_audits since there is no user_id available.

        return NextResponse.json({ analysis: response.text })

    } catch (error: unknown) {
        console.error('Video Autopsy Error:', error)
        return NextResponse.json(
            { error: (error as Error)?.message || 'An unexpected error occurred during the autopsy' },
            { status: 500 }
        )
    }
}
