import { createClient } from '@/lib/supabase/server'
import { NextResponse } from 'next/server'
import { GoogleGenAI } from '@google/genai'

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY })

export async function POST(req: Request) {
    try {
        const supabase = await createClient()

        // 1. Get stored tokens to identify the user
        const { data: tokenRow, error: tokenErr } = await supabase
            .from('youtube_tokens')
            .select('*')
            .limit(1)
            .single()
        
        if (tokenErr || !tokenRow) {
            return NextResponse.json({ error: 'Unauthorized or YouTube not connected' }, { status: 401 })
        }

        const body = await req.json()
        const { script } = body

        if (!script) {
            return NextResponse.json({ error: 'Script text is required' }, { status: 400 })
        }

        const prompt = `
You are an elite YouTube scriptwriter and engagement expert.
Please review the following script/hook for a YouTube video:

SCRIPT:
"""
${script}
"""

Provide a "Script Rater" report in Markdown format.
Include:
1. Hook Score (1-10) with brief justification.
2. Emotional Payoff (Does the viewer know why they should keep watching?)
3. 2 Alternative Hook Rewrites (One curiosity-driven, one bold/authoritative).
`

        // Call Gemini (Using 2.5 flash for high-speed text analysis)
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: prompt,
            config: {
                temperature: 0.7,
            }
        })

        if (!response.text) {
            throw new Error('No text generated by Gemini')
        }

        // Note: Skipped storing into youtube_audits since there is no user_id available.

        return NextResponse.json({ analysis: response.text })

    } catch (error: unknown) {
        console.error('Script Rater Error:', error)
        return NextResponse.json(
            { error: (error as Error)?.message || 'An unexpected error occurred during script rating' },
            { status: 500 }
        )
    }
}
