/**
 * POST /api/export — Export content in various formats
 * 
 * Formats:
 * - txt: Plain text (default)
 * - pdf: PDF document with formatting
 * - gdoc: Create Google Doc and return URL
 * - youtube: YouTube creator format (script + thumbnail)
 * 
 * Requires authentication.
 */
import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { chromium } from 'playwright'

export const maxDuration = 60

interface ExportRequest {
  itemId: string
  format: 'txt' | 'pdf' | 'gdoc' | 'youtube'
}

export async function POST(req: NextRequest) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const { itemId, format = 'txt' }: ExportRequest = await req.json().catch(() => ({}))

  if (!itemId) {
    return NextResponse.json({ error: 'itemId required' }, { status: 400 })
  }

  try {
    // Fetch content item
    const { data: item, error } = await supabase
      .from('content_items')
      .select('*')
      .eq('id', itemId)
      .eq('user_id', user.id)
      .single()

    if (error || !item) {
      return NextResponse.json({ error: 'Content not found' }, { status: 404 })
    }

    const sd = item.script_data || {}
    const scenes = sd.scenes || []
    const contentType = item.content_type

    switch (format) {
      case 'txt': {
        const text = formatAsText(item, sd, scenes)
        return NextResponse.json({
          format: 'txt',
          filename: `${item.title || 'content'}.txt`,
          content: text,
          mimeType: 'text/plain',
        })
      }

      case 'pdf': {
        const html = formatAsHTML(item, sd, scenes, contentType)
        const pdfBuffer = await generatePDF(html)
        
        // Return as base64 for client download
        return NextResponse.json({
          format: 'pdf',
          filename: `${item.title || 'content'}.pdf`,
          content: pdfBuffer.toString('base64'),
          mimeType: 'application/pdf',
          base64: true,
        })
      }

      case 'youtube': {
        const youtubeFormat = formatForYouTube(item, sd, scenes)
        return NextResponse.json({
          format: 'txt',
          filename: `${item.title || 'video'} - YouTube Script.txt`,
          content: youtubeFormat,
          mimeType: 'text/plain',
        })
      }

      case 'gdoc': {
        // For now, return the content formatted for Google Docs
        // Full Google Docs API integration would require OAuth setup
        const gdocFormat = formatForGoogleDocs(item, sd, scenes)
        return NextResponse.json({
          format: 'gdoc-ready',
          filename: `${item.title || 'content'}`,
          content: gdocFormat,
          instructions: 'Copy this content and paste into Google Docs',
          mimeType: 'text/html',
        })
      }

      default:
        return NextResponse.json({ error: 'Unsupported format' }, { status: 400 })
    }

  } catch (err: any) {
    console.error('[Export] Failed:', err)
    return NextResponse.json({ error: err.message }, { status: 500 })
  }
}

function formatAsText(item: any, sd: any, scenes: any[]): string {
  let text = `${item.title}\n${'='.repeat(item.title.length)}\n\n`
  
  if (item.hook) {
    text += `HOOK: "${item.hook}"\n\n`
  }

  if (scenes.length > 0) {
    scenes.forEach((s: any, i: number) => {
      const label = s.block_label || `Scene ${s.scene_number || i + 1}`
      const duration = s.duration_seconds ? ` (${s.duration_seconds}s)` : ''
      text += `[${label}${duration}]\n`
      text += `${s.script_text || s.voiceover || ''}\n`
      if (s.visual_direction || s.visual) {
        text += `\nVisual: ${s.visual_direction || s.visual}\n`
      }
      if (s.on_screen_text) {
        text += `On-screen: "${s.on_screen_text}"\n`
      }
      text += '\n'
    })
  } else if (sd.headline) {
    text += `${sd.headline}\n\n${sd.primaryText || sd.body || ''}\n`
  } else if (sd.caption) {
    text += `${sd.caption}\n`
  }

  if (sd.hashtags?.length) {
    text += `\nHASHTAGS:\n${sd.hashtags.join(' ')}\n`
  }

  if (sd.cta || item.cta) {
    text += `\nCTA: ${sd.cta || item.cta}\n`
  }

  text += `\n---\nGenerated by Creative Studio\n${new Date().toLocaleDateString()}`
  
  return text
}

function formatAsHTML(item: any, sd: any, scenes: any[], contentType: string): string {
  const hook = item.hook || sd.hook || ''
  const hashtags = sd.hashtags || []
  const cta = sd.cta || item.cta || ''
  
  let scenesHTML = ''
  if (scenes.length > 0) {
    scenesHTML = scenes.map((s: any) => {
      const label = s.block_label || `Scene ${s.scene_number || '?'}`
      const duration = s.duration_seconds ? `<span class="duration">${s.duration_seconds}s</span>` : ''
      const visual = s.visual_direction || s.visual ? `<div class="visual">🎥 ${s.visual_direction || s.visual}</div>` : ''
      const onScreen = s.on_screen_text ? `<div class="on-screen">"${s.on_screen_text}"</div>` : ''
      
      return `
        <div class="scene">
          <div class="scene-header">
            <span class="scene-label">${label}</span>
            ${duration}
          </div>
          <div class="scene-text">${s.script_text || s.voiceover || ''}</div>
          ${visual}
          ${onScreen}
        </div>
      `
    }).join('')
  }

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${item.title}</title>
  <style>
    @page { margin: 1in; }
    * { box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      color: #1a1a1a;
      max-width: 800px;
      margin: 0 auto;
      padding: 2rem;
    }
    .header {
      border-bottom: 3px solid #7c3aed;
      padding-bottom: 1rem;
      margin-bottom: 2rem;
    }
    h1 {
      font-size: 1.75rem;
      font-weight: 700;
      margin: 0 0 0.5rem 0;
      color: #1a1a1a;
    }
    .meta {
      font-size: 0.875rem;
      color: #6b7280;
    }
    .hook {
      background: #f3f4f6;
      border-left: 4px solid #7c3aed;
      padding: 1rem;
      margin: 1.5rem 0;
      font-style: italic;
    }
    .scene {
      margin: 1.5rem 0;
      padding: 1rem;
      background: #fafafa;
      border-radius: 8px;
    }
    .scene-header {
      display: flex;
      align-items: center;
      gap: 0.75rem;
      margin-bottom: 0.75rem;
    }
    .scene-label {
      font-weight: 600;
      color: #7c3aed;
      text-transform: uppercase;
      font-size: 0.75rem;
      letter-spacing: 0.05em;
    }
    .duration {
      font-size: 0.75rem;
      color: #6b7280;
      background: #e5e7eb;
      padding: 0.125rem 0.5rem;
      border-radius: 4px;
    }
    .scene-text {
      font-size: 1rem;
      line-height: 1.7;
    }
    .visual {
      margin-top: 0.75rem;
      font-size: 0.875rem;
      color: #6b7280;
      font-style: italic;
    }
    .on-screen {
      margin-top: 0.5rem;
      font-weight: 600;
      color: #1a1a1a;
    }
    .footer {
      margin-top: 3rem;
      padding-top: 1rem;
      border-top: 1px solid #e5e7eb;
      font-size: 0.875rem;
      color: #6b7280;
    }
    .hashtags {
      color: #3b82f6;
      margin-top: 1rem;
    }
    .cta {
      background: #7c3aed;
      color: white;
      padding: 0.75rem 1rem;
      border-radius: 6px;
      margin-top: 1rem;
      font-weight: 600;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${item.title}</h1>
    <div class="meta">${contentType} • ${item.platform || 'Multi-platform'}</div>
  </div>
  
  ${hook ? `<div class="hook">"${hook}"</div>` : ''}
  
  ${scenesHTML}
  
  ${hashtags.length ? `<div class="hashtags">${hashtags.map((h: string) => '#' + h.replace('#', '')).join(' ')}</div>` : ''}
  
  ${cta ? `<div class="cta">${cta}</div>` : ''}
  
  <div class="footer">
    Generated by Creative Studio • ${new Date().toLocaleDateString()}
  </div>
</body>
</html>
  `.trim()
}

function formatForYouTube(item: any, sd: any, scenes: any[]): string {
  let text = `YOUTUBE VIDEO SCRIPT\n${'='.repeat(50)}\n\n`
  
  text += `TITLE: ${item.title}\n`
  text += `PLATFORM: YouTube\n`
  text += `TYPE: ${sd.video_type || 'Tutorial'}\n`
  text += `LENGTH: ${sd.total_duration_estimate || '8-12 minutes'}\n\n`
  
  if (sd.title_options?.length) {
    text += `TITLE OPTIONS:\n`
    sd.title_options.forEach((t: string, i: number) => {
      text += `  ${i + 1}. ${t}\n`
    })
    text += '\n'
  }
  
  text += `${'─'.repeat(50)}\n\n`
  
  // Script sections
  const sections = sd.sections || scenes
  if (sections?.length > 0) {
    sections.forEach((s: any, i: number) => {
      const name = s.name || s.block_label || `Section ${i + 1}`
      const duration = s.duration || (s.duration_seconds ? `${s.duration_seconds}s` : '')
      
      text += `[${name}${duration ? ` - ${duration}` : ''}]\n\n`
      text += `SCRIPT:\n${s.speaking_lines || s.script_text || ''}\n\n`
      
      if (s.visual_notes || s.visual_direction || s.visual) {
        text += `VISUALS:\n${s.visual_notes || s.visual_direction || s.visual}\n\n`
      }
      
      if (s.tips) {
        text += `PRO TIPS:\n${s.tips}\n\n`
      }
      
      text += `${'─'.repeat(30)}\n\n`
    })
  }
  
  // Thumbnail concept
  if (sd.thumbnail_concept) {
    text += `THUMBNAIL CONCEPT:\n${sd.thumbnail_concept}\n\n`
  }
  
  // SEO metadata
  if (sd.description) {
    text += `DESCRIPTION:\n${sd.description}\n\n`
  }
  
  if (sd.tags?.length) {
    text += `TAGS:\n${sd.tags.join(', ')}\n\n`
  }
  
  text += `${'='.repeat(50)}\n`
  text += `Ready to film! 🎬\n`
  
  return text
}

function formatForGoogleDocs(item: any, sd: any, scenes: any[]): string {
  // Returns HTML that pastes well into Google Docs
  return formatAsHTML(item, sd, scenes, item.content_type)
}

async function generatePDF(html: string): Promise<Buffer> {
  const browser = await chromium.launch({ headless: true })
  const context = await browser.newContext()
  const page = await context.newPage()
  
  await page.setContent(html, { waitUntil: 'networkidle' })
  
  const pdfBuffer = await page.pdf({
    format: 'A4',
    printBackground: true,
    margin: { top: '1in', right: '1in', bottom: '1in', left: '1in' }
  })
  
  await browser.close()
  
  return Buffer.from(pdfBuffer)
}