import { createClient } from '@/lib/supabase/server'
import { NextResponse } from 'next/server'
import { GoogleGenAI } from '@google/genai'

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY })

export async function POST(req: Request) {
    try {
        const supabase = await createClient()

        // 1. Get stored tokens to identify the user
        const { data: tokenRow, error: tokenErr } = await supabase
            .from('youtube_tokens')
            .select('*')
            .limit(1)
            .single()
        
        if (tokenErr || !tokenRow) {
            return NextResponse.json({ error: 'Unauthorized or YouTube not connected' }, { status: 401 })
        }

        const body = await req.json()
        const { title, imageBase64 } = body

        if (!title || !imageBase64) {
            return NextResponse.json({ error: 'Title and image are required' }, { status: 400 })
        }

        // Parse base64
        const matches = imageBase64.match(/^data:(image\/[a-zA-Z]+);base64,(.*)$/)
        let mimeType = 'image/jpeg'
        let base64Data = imageBase64

        if (matches) {
            mimeType = matches[1]
            base64Data = matches[2]
        }

        const prompt = `
You are a YouTube CTR optimization expert.
Review the following thumbnail image and video title.

TITLE: "${title}"

Provide a "Thumbnail & Title Simulator" report in Markdown format.
Include:
1. Expected CTR Potential (High/Medium/Low) based on current YouTube trends.
2. Visual Clarity & Contrast (Does the thumbnail pop? Is the text readable on mobile?)
3. Title/Thumbnail Synergy (Do they complement each other or just repeat the same words?)
4. 2 Alternative Titles (One curiosity-focused, one strictly benefit-driven).
`

        // Call Gemini Vision (gemini-2.5-flash supports multimodal inputs)
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: [
                { text: prompt },
                {
                    inlineData: {
                        data: base64Data,
                        mimeType: mimeType
                    }
                }
            ],
            config: {
                temperature: 0.7,
            }
        })

        if (!response.text) {
            throw new Error('No text generated by Gemini')
        }

        // Note: Skipped storing into youtube_audits since there is no user_id available.

        return NextResponse.json({ analysis: response.text })

    } catch (error: unknown) {
        console.error('Thumbnail Simulator Error:', error)
        return NextResponse.json(
            { error: (error as Error)?.message || 'An unexpected error occurred during thumbnail simulation' },
            { status: 500 }
        )
    }
}
